//
//  main.c
//  29
//
//  Created by Tyler Niiyama on 12/31/17.
//  Copyright © 2017 Tyler Niiyama. All rights reserved.
//

// Find the number of distinct terms in the sequence generated by a^b for 2 ≤ a, b ≤ 100

#include <stdio.h>
#include <math.h>

int check_power(int x);
int is_prime(int x);

int main(void)
{
    int sum = 0;
    for (int a = 2; a < 101; a++)
    {
        if (check_power(a) != 0)
        {
            continue;
        }
        else
        {
            int power = 2;
            // adds 99 terms, 2-100
            sum = sum + 99;
            // checks all powers of a less than 101
            while (pow(a, power) < 101)
            {
                for (int b = 2; b < 101; b++)
                {
                    int check = power - 1;
                    while (check > 0)
                    {
                        if (((b * power) % check == 0) && (b * power < check * 100))
                        {
                            break;
                        }
                        check--;
                    }
                    if (check == 0)
                    {
                        sum++;
                    }
                }
                power++;
            }
        }
    }
    printf("%i\n", sum);
    return 0;
}

// checks if the input can be expressed as a lower base power
// returns the lower base if possible, returns 0 otherwise
int check_power(int x)
{
    switch(x)
    {
        case 2: return 0;
        case 3: return 0;
        case 4: return 1;
        case 5: return 0;
        case 6: return 0;
        case 7: return 0;
        case 8: return 1;
        case 9: return 1;
        case 10: return 0;
    }
    int base = 2;
    // goes through potential bases
    while (base < ceil(sqrt(x)) + 1)
    {
        int y = x;
        // if you can repeatedly divide the input down to 1, it's a power
        while (y % base == 0)
        {
            y = y / base;
            if (y == 1)
            {
                return base;
            }
        }
        base++;
    }
    return 0;
}

// check if prime
int is_prime(int x)
{
    if (x < 1)
    {
        return 0;
    }
    int k = 1, a = 0, b = 0;
    long n;
    switch(x)
    {
        case 1: return 0;
        case 2: return 1;
        case 3: return 1;
        case 4: return 0;
        case 5: return 1;
        case 6: return 0;
        case 7: return 1;
    }
    if (x % 2 == 0 || x % 3 == 0)
    {
        return 0;
    }
    n = (int) sqrt(x);
    while (b < n)
    {
        a = (6 * k) - 1;
        b = (6 * k) + 1;
        if (x % a == 0 || x % b == 0)
        {
            return 0;
        }
        k++;
    }
    return 1;
}
